#!/usr/bin/env bash
# Opt-in real Herdr transport test. Requires the approved Firstmate lab helper.
set -euo pipefail
: "${HERDR_LAB_HELPER:?Set HERDR_LAB_HELPER to the approved fm-herdr-lab.sh}"
cd "$(dirname "$0")/.."
root=$(pwd -P)
HERDR_LAB_SESSION=$("$HERDR_LAB_HELPER" name pi-herdr-context)
trap '"$HERDR_LAB_HELPER" teardown "$HERDR_LAB_SESSION"' EXIT
"$HERDR_LAB_HELPER" provision "$HERDR_LAB_SESSION"
lab() { "$HERDR_LAB_HELPER" run "$HERDR_LAB_SESSION" "$@"; }
HERDR_CONFIG_PATH="$root/.config/herdr/config.toml" lab config check
workspace=$(lab workspace create --cwd "$root" --label context-lab --no-focus \
  --env "HERDR_LAB_HELPER=$HERDR_LAB_HELPER")
pane=$(printf '%s' "$workspace" | jq -er '.result.root_pane.pane_id')
# Paths here are generated by this test, shell-quoted with Bash printf %q.
printf -v command 'node %q; printf "CONTEXT_LAB_EXIT=%%s\\n" "$?"' "$root/tests/herdr_context_lab.mjs"
lab pane send-text "$pane" "$command"
lab pane send-keys "$pane" enter
if ! output=$(lab pane wait-output "$pane" --regex '^CONTEXT_LAB_EXIT=[0-9]+$' --timeout 45000); then
  lab pane read "$pane" --lines 80
  exit 1
fi
printf '%s\n' "$output" | jq -e '.result.matched_line == "CONTEXT_LAB_EXIT=0" and (.result.read.text | contains("CONTEXT_LAB_PASS"))'
lab pane get "$pane" | jq -e '.result.pane.tokens.pi_context == null'
